from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pathlib import Path
from contextlib import asynccontextmanager
from datetime import datetime, time, timedelta
from zoneinfo import ZoneInfo

import os
import json
import pandas as pd
import subprocess
import sys
import threading
import time as time_module


# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_DIR / "data"
NOTEBOOKS_DIR = PROJECT_DIR / "notebooks"

PIPELINE_SCRIPT = NOTEBOOKS_DIR / "19_daily_pipeline.py"
PRODUCTION_PREDICTION_FILE = DATA_DIR / "latest_production_prediction.json"

IST = ZoneInfo("Asia/Kolkata")


# ============================================================
# PIPELINE STATE
# ============================================================

pipeline_lock = threading.Lock()

pipeline_status = {
    "running": False,
    "last_started": None,
    "last_completed": None,
    "last_status": "never_run",
    "last_error": None,
}

# Prevent the automatic scheduler from triggering the same
# pipeline multiple times during the 15:45-15:50 window.
last_automatic_trigger_date = None


# ============================================================
# DAILY RUN TRACKER
# ============================================================

RUN_MARKER = DATA_DIR / ".last_pipeline_run"


def get_last_pipeline_date():
    """
    Return the date on which the pipeline last completed
    successfully.
    """

    if not RUN_MARKER.exists():
        return None

    try:
        value = RUN_MARKER.read_text(
            encoding="utf-8"
        ).strip()

        if not value:
            return None

        return datetime.strptime(
            value,
            "%Y-%m-%d"
        ).date()

    except Exception:
        return None


def mark_pipeline_complete():
    """
    Record today's date after a successful pipeline.
    """

    DATA_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    today = datetime.now(
        IST
    ).date()

    RUN_MARKER.write_text(
        today.strftime("%Y-%m-%d"),
        encoding="utf-8"
    )


# ============================================================
# FASTAPI LIFESPAN
# ============================================================

@asynccontextmanager
async def lifespan(app: FastAPI):

    print("=" * 70)
    print("MURTAZA LABS NIFTY INTELLIGENCE API")
    print("=" * 70)
    print("Automatic daily pipeline scheduler: ENABLED")
    print("Timezone: Asia/Kolkata")
    print("Scheduled pipeline time: 15:45 IST")
    print("=" * 70)

    scheduler_thread = threading.Thread(
        target=automatic_pipeline_scheduler,
        daemon=True
    )

    scheduler_thread.start()

    yield

    print("API shutting down...")


# ============================================================
# FASTAPI APP
# ============================================================

app = FastAPI(
    title="Murtaza Labs NIFTY Intelligence API",
    lifespan=lifespan
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5174",
        "https://murtaza-labs-nifty-intelligence-xh5.vercel.app",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# BOOLEAN PARSER
# ============================================================

def parse_bool(value):

    if pd.isna(value):
        return None

    if isinstance(value, bool):
        return value

    value = str(value).strip().lower()

    if value in [
        "true",
        "1",
        "yes"
    ]:
        return True

    if value in [
        "false",
        "0",
        "no"
    ]:
        return False

    return None


# ============================================================
# PRODUCTION PREDICTION
# ============================================================

def get_production_prediction_data():
    """
    Read the prediction generated by:
        notebooks/15_live_prediction_production.py

    This is the single source of truth for the live production
    prediction shown by the website.
    """

    if not PRODUCTION_PREDICTION_FILE.exists():
        return None

    try:
        with open(
            PRODUCTION_PREDICTION_FILE,
            "r",
            encoding="utf-8",
        ) as f:
            data = json.load(f)

        if not isinstance(data, dict):
            return None

        data["available"] = True
        return data

    except Exception as e:
        print(
            "Production prediction read error:",
            str(e),
        )
        return None


# ============================================================
# MARKET SNAPSHOT HELPERS
# ============================================================

def load_market_dataframe(limit=400):
    """Load chronological market history with enough rows for 200-day indicators."""
    file = DATA_DIR / "live_market_data.csv"
    if not file.exists():
        return pd.DataFrame()

    try:
        df = pd.read_csv(file)
        if df.empty:
            return df

        if "Date" in df.columns:
            parsed_dates = pd.to_datetime(df["Date"], errors="coerce")
            df = df.assign(_parsed_date=parsed_dates)
            df = df.sort_values("_parsed_date", kind="stable")
            df = df.drop(columns=["_parsed_date"])

        return df.tail(limit).reset_index(drop=True)
    except Exception as exc:
        print("Market snapshot error:", str(exc))
        return pd.DataFrame()


def numeric_or_none(value, zero_is_missing=False):
    try:
        if value is None or value == "":
            return None
        number = float(value)
        if pd.isna(number) or not pd.api.types.is_number(number):
            return None
        if zero_is_missing and number <= 0:
            return None
        return number
    except Exception:
        return None


def derive_market_snapshot():
    """Derive trustworthy display-only values from the market history."""
    df = load_market_dataframe(400)
    if df.empty or "Close" not in df.columns:
        return {}

    closes = pd.to_numeric(df["Close"], errors="coerce").dropna()
    snapshot = {}

    if len(closes) >= 2 and float(closes.iloc[-2]) != 0:
        snapshot["day_change_pct"] = (
            (float(closes.iloc[-1]) / float(closes.iloc[-2]) - 1.0) * 100.0
        )

    # India VIX is never a meaningful zero. Treat zero/missing as unavailable.
    for column in ("India_VIX", "India_VIX_Close", "VIX"):
        if column in df.columns:
            series = pd.to_numeric(df[column], errors="coerce").dropna()
            if not series.empty and float(series.iloc[-1]) > 0:
                snapshot["india_vix"] = float(series.iloc[-1])
                break

    return snapshot


# ============================================================
# DASHBOARD DATA
# ============================================================

def get_dashboard_data():
    """
    Return dashboard data.

    Production prediction is preferred whenever
    latest_production_prediction.json exists. The legacy
    live_prediction.csv remains as a fallback so the rest of
    the existing dashboard continues to work.
    """

    production = get_production_prediction_data()
    market_snapshot = derive_market_snapshot()

    history_file = DATA_DIR / "prediction_history.csv"

    history = pd.DataFrame()

    if history_file.exists():
        history = pd.read_csv(history_file)

    correct_values = []

    if (
        not history.empty
        and "Correct" in history.columns
    ):
        for value in history["Correct"]:
            parsed = parse_bool(value)

            if parsed is not None:
                correct_values.append(parsed)

    verified = len(correct_values)
    correct = sum(correct_values)

    accuracy = None

    if verified > 0:
        accuracy = (
            correct / verified
        ) * 100

    # --------------------------------------------------------
    # PRODUCTION MODEL OUTPUT
    # --------------------------------------------------------

    if production is not None:

        prediction = str(
            production.get(
                "prediction",
                "UNKNOWN",
            )
        )

        probability_up = float(
            production.get(
                "probability_up",
                0,
            )
        )

        probability_down = float(
            production.get(
                "probability_down",
                0,
            )
        )

        confidence = float(
            production.get(
                "confidence",
                0,
            )
        )

        nifty_close = float(
            production.get(
                "nifty_close",
                0,
            )
        )

        date = str(
            production.get(
                "prediction_date",
                "",
            )
        )

        return {
            "date": date,

            "nifty_close": nifty_close,

            "prediction": prediction,

            "probability_up": probability_up,

            "probability_down": probability_down,

            "confidence": confidence,

            "signal": prediction,

            "total_predictions": int(
                len(history)
            ),

            "verified_predictions": int(
                verified
            ),

            "correct": int(
                correct
            ),

            "accuracy": accuracy,

            "backend": "online",

            "prediction_source":
                "production_model",

            "production_model":
                production.get(
                    "model",
                    "CATBOOST_PRODUCTION",
                ),

            "model_trained_through":
                production.get(
                    "model_trained_through"
                ),

            "feature_count":
                int(
                    production.get(
                        "feature_count",
                        0,
                    )
                ),

            "rsi_14":
                production.get(
                    "rsi_14"
                ),

            "macd":
                production.get(
                    "macd"
                ),

            "day_change_pct":
                market_snapshot.get(
                    "day_change_pct",
                    numeric_or_none(production.get("day_change_pct"))
                ),

            "india_vix":
                market_snapshot.get(
                    "india_vix",
                    numeric_or_none(production.get("india_vix"), zero_is_missing=True)
                ),

            "banknifty_return_1d":
                production.get(
                    "banknifty_return_1d"
                ),

            "sp500_return_1d":
                production.get(
                    "sp500_return_1d"
                ),

            "usdinr_return_1d":
                production.get(
                    "usdinr_return_1d"
                ),

            "gold_return_1d":
                production.get(
                    "gold_return_1d"
                ),

            "crude_return_1d":
                production.get(
                    "crude_return_1d"
                ),

            "trend_regime":
                production.get(
                    "trend_regime"
                ),

            "volatility_regime":
                production.get(
                    "volatility_regime"
                ),

            "risk_score":
                production.get(
                    "risk_score"
                ),

            "pipeline_running":
                pipeline_status["running"],

            "last_pipeline_status":
                pipeline_status["last_status"],

            "last_pipeline_completed":
                pipeline_status["last_completed"],
        }

    # --------------------------------------------------------
    # LEGACY FALLBACK
    # --------------------------------------------------------

    prediction_file = DATA_DIR / "live_prediction.csv"

    if not prediction_file.exists():
        raise HTTPException(
            status_code=404,
            detail=(
                "No production prediction or "
                "live_prediction.csv found"
            ),
        )

    prediction_df = pd.read_csv(
        prediction_file
    )

    if prediction_df.empty:
        raise HTTPException(
            status_code=404,
            detail="No prediction available",
        )

    latest = prediction_df.iloc[-1]

    return {
        "date": str(
            latest.get(
                "Prediction_Date",
                "",
            )
        ),

        "nifty_close": float(
            latest.get(
                "NIFTY_Close",
                0,
            )
        ),

        "prediction": str(
            latest.get(
                "Prediction",
                "UNKNOWN",
            )
        ),

        "probability_up": float(
            latest.get(
                "Probability_UP",
                0,
            )
        ),

        "probability_down": float(
            latest.get(
                "Probability_DOWN",
                0,
            )
        ),

        "confidence": float(
            latest.get(
                "Confidence",
                0,
            )
        ),

        "signal": str(
            latest.get(
                "Signal",
                "UNKNOWN",
            )
        ),

        "total_predictions": int(
            len(history)
        ),

        "verified_predictions": int(
            verified
        ),

        "correct": int(
            correct
        ),

        "accuracy": accuracy,

        "backend": "online",

        "prediction_source":
            "legacy_live_prediction",

        "pipeline_running":
            pipeline_status["running"],

        "last_pipeline_status":
            pipeline_status["last_status"],

        "last_pipeline_completed":
            pipeline_status["last_completed"],
    }


# ============================================================
# HEALTH
# ============================================================

@app.get("/api/health")
def health():

    return {

        "status": "online",

        "service":
            "Murtaza Labs NIFTY Intelligence API",

        "pipeline_running":
            pipeline_status["running"],

        "last_pipeline_status":
            pipeline_status["last_status"],

        "last_pipeline_completed":
            pipeline_status["last_completed"],
    }


# ============================================================
# PIPELINE STATUS
# ============================================================

@app.get("/api/pipeline-status")
def pipeline_status_endpoint():

    last_pipeline_date = (
        get_last_pipeline_date()
    )

    return {

        "running":
            pipeline_status["running"],

        "last_started":
            pipeline_status["last_started"],

        "last_completed":
            pipeline_status["last_completed"],

        "last_status":
            pipeline_status["last_status"],

        "last_error":
            pipeline_status["last_error"],

        "last_pipeline_date":
            str(last_pipeline_date)
            if last_pipeline_date
            else None,
    }


# ============================================================
# DASHBOARD
# ============================================================

@app.get("/api/dashboard")
def dashboard():

    return get_dashboard_data()


# ============================================================
# PRODUCTION PREDICTION ENDPOINT
# ============================================================

@app.get("/api/production-prediction")
def production_prediction():

    data = get_production_prediction_data()

    if data is None:
        raise HTTPException(
            status_code=404,
            detail=(
                "latest_production_prediction.json "
                "not found. Run "
                "15_live_prediction_production.py first."
            ),
        )

    return data


# ============================================================
# HISTORY
# ============================================================

@app.get("/api/history")
def history():

    file = (
        DATA_DIR /
        "prediction_history.csv"
    )

    if not file.exists():
        return []

    df = pd.read_csv(
        file
    )

    df = df.where(
        pd.notnull(df),
        None
    )

    return df.to_dict(
        orient="records"
    )


# ============================================================
# MARKET DATA
# ============================================================

@app.get("/api/market")
def market():

    file = (
        DATA_DIR /
        "live_market_data.csv"
    )

    if not file.exists():

        raise HTTPException(
            status_code=404,
            detail="live_market_data.csv not found"
        )

    try:

        df = load_market_dataframe(400).copy()

        if "Date" in df.columns:

            df["Date"] = (
                df["Date"]
                .astype(str)
            )

        df = df.replace(
            [
                float("inf"),
                float("-inf")
            ],
            None
        )

        df = (
            df.astype(object)
            .where(
                pd.notna(df),
                None
            )
        )

        return df.to_dict(
            orient="records"
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                f"Market data error: {str(e)}"
            )
        )


# ============================================================
# DOWNLOAD CURRENT PREDICTION
# ============================================================

@app.get("/api/download/prediction")
def download_prediction():

    file = (
        DATA_DIR /
        "live_prediction.csv"
    )

    if not file.exists():

        raise HTTPException(
            status_code=404,
            detail="Prediction file not found"
        )

    return FileResponse(

        path=file,

        filename=(
            "murtaza-labs-live-prediction.csv"
        ),

        media_type="text/csv"
    )


# ============================================================
# DOWNLOAD PRODUCTION PREDICTION
# ============================================================

@app.get("/api/download/production-prediction")
def download_production_prediction():

    file = DATA_DIR / "latest_production_prediction.json"

    if not file.exists():
        raise HTTPException(
            status_code=404,
            detail=(
                "latest_production_prediction.json "
                "not found"
            ),
        )

    return FileResponse(
        path=file,
        filename=(
            "murtaza-labs-production-prediction.json"
        ),
        media_type="application/json",
    )


# ============================================================
# DOWNLOAD HISTORY
# ============================================================

@app.get("/api/download/history")
def download_history():

    file = (
        DATA_DIR /
        "prediction_history.csv"
    )

    if not file.exists():

        raise HTTPException(
            status_code=404,
            detail="Prediction history not found"
        )

    return FileResponse(

        path=file,

        filename=(
            "murtaza-labs-prediction-history.csv"
        ),

        media_type="text/csv"
    )


# ============================================================
# ACTUAL PIPELINE EXECUTION
# ============================================================

def run_pipeline_background(
    source="manual"
):

    try:

        pipeline_status["running"] = True

        pipeline_status["last_started"] = (
            datetime.now(
                IST
            ).isoformat()
        )

        pipeline_status["last_status"] = (
            "running"
        )

        pipeline_status["last_error"] = None

        print()
        print("=" * 70)
        print(
            f"NIFTY PIPELINE STARTED "
            f"({source.upper()})"
        )
        print("=" * 70)

        # ----------------------------------------------------
        # Check that the pipeline exists.
        # ----------------------------------------------------

        if not PIPELINE_SCRIPT.exists():

            raise FileNotFoundError(
                "Pipeline script not found: "
                f"{PIPELINE_SCRIPT}"
            )

        # ----------------------------------------------------
        # UTF-8 ENVIRONMENT FIX
        #
        # This is the important fix.
        #
        # Your 14_live_data.py contains Unicode characters
        # such as:
        #
        #     →
        #
        # Windows CP1252 cannot encode them.
        #
        # These environment variables force the child Python
        # process to use UTF-8.
        # ----------------------------------------------------

        env = os.environ.copy()

        env["PYTHONUNBUFFERED"] = "1"

        env["PYTHONIOENCODING"] = "utf-8"

        env["PYTHONUTF8"] = "1"

        # ----------------------------------------------------
        # Launch the pipeline.
        # ----------------------------------------------------

        result = subprocess.run(

            [
                sys.executable,

                "-X",
                "utf8",

                "-u",

                str(
                    PIPELINE_SCRIPT
                )
            ],

            cwd=str(
                PROJECT_DIR
            ),

            capture_output=True,

            text=True,

            encoding="utf-8",

            errors="replace",

            timeout=600,

            env=env
        )

        stdout = (
            result.stdout
            or ""
        )

        stderr = (
            result.stderr
            or ""
        )

        # ----------------------------------------------------
        # PRINT STDOUT
        # ----------------------------------------------------

        print()
        print("=" * 70)
        print(
            "DAILY PIPELINE STDOUT"
        )
        print("=" * 70)

        if stdout.strip():

            print(
                stdout
            )

        else:

            print(
                "(no stdout)"
            )

        # ----------------------------------------------------
        # PRINT STDERR
        # ----------------------------------------------------

        print()
        print("=" * 70)
        print(
            "DAILY PIPELINE STDERR"
        )
        print("=" * 70)

        if stderr.strip():

            print(
                stderr
            )

        else:

            print(
                "(no stderr)"
            )

        # ----------------------------------------------------
        # EXIT CODE
        # ----------------------------------------------------

        print()
        print(
            f"PIPELINE EXIT CODE: "
            f"{result.returncode}"
        )

        print("=" * 70)

        # ----------------------------------------------------
        # PIPELINE FAILED
        # ----------------------------------------------------

        if result.returncode != 0:

            error_text = (
                stderr.strip()
            )

            if not error_text:

                error_text = (
                    stdout.strip()
                )

            if not error_text:

                error_text = (
                    "Pipeline exited "
                    f"with code "
                    f"{result.returncode}"
                )

            # Keep the most useful portion of the error.
            pipeline_status["last_error"] = (
                error_text[-5000:]
            )

            pipeline_status["last_status"] = (
                "failed"
            )

            print()
            print("=" * 70)
            print(
                "NIFTY PIPELINE FAILED"
            )
            print("=" * 70)

            print(
                pipeline_status[
                    "last_error"
                ]
            )

            print("=" * 70)

            return

        # ----------------------------------------------------
        # PIPELINE SUCCESS
        # ----------------------------------------------------

        mark_pipeline_complete()

        pipeline_status["last_status"] = (
            "completed"
        )

        pipeline_status["last_completed"] = (
            datetime.now(
                IST
            ).isoformat()
        )

        pipeline_status["last_error"] = None

        print()
        print("=" * 70)
        print(
            "NIFTY PIPELINE COMPLETED "
            "SUCCESSFULLY"
        )
        print("=" * 70)

    # --------------------------------------------------------
    # TIMEOUT
    # --------------------------------------------------------

    except subprocess.TimeoutExpired as e:

        pipeline_status["last_status"] = (
            "timeout"
        )

        pipeline_status["last_error"] = (
            "Pipeline exceeded "
            "the 10 minute timeout."
        )

        print()
        print("=" * 70)
        print(
            "NIFTY PIPELINE TIMEOUT"
        )
        print("=" * 70)

        if getattr(
            e,
            "stderr",
            None
        ):

            print(
                e.stderr
            )

    # --------------------------------------------------------
    # OTHER ERROR
    # --------------------------------------------------------

    except Exception as e:

        pipeline_status["last_status"] = (
            "failed"
        )

        pipeline_status["last_error"] = (
            str(e)
        )

        print()
        print("=" * 70)
        print(
            "NIFTY PIPELINE ERROR"
        )
        print("=" * 70)

        print(
            str(e)
        )

        print("=" * 70)

    finally:

        pipeline_status["running"] = False

        # The lock is acquired before this function is started.
        try:

            pipeline_lock.release()

        except RuntimeError:

            pass


# ============================================================
# MANUAL PIPELINE BUTTON
# ============================================================

@app.post("/api/run-pipeline")
def run_pipeline():

    if pipeline_status["running"]:

        return {

            "status":
                "already_running",

            "message":
                "Daily pipeline is already running."
        }

    acquired = (
        pipeline_lock.acquire(
            blocking=False
        )
    )

    if not acquired:

        return {

            "status":
                "already_running",

            "message":
                "Daily pipeline is already running."
        }

    thread = threading.Thread(

        target=run_pipeline_background,

        kwargs={
            "source": "manual"
        },

        daemon=True
    )

    thread.start()

    return {

        "status":
            "started",

        "message":
            "Daily pipeline started."
    }


# ============================================================
# AUTOMATIC PIPELINE
# ============================================================

def start_automatic_pipeline():

    global last_automatic_trigger_date

    today = datetime.now(
        IST
    ).date()

    # --------------------------------------------------------
    # Weekend protection
    # --------------------------------------------------------

    if today.weekday() >= 5:

        print(
            "Automatic pipeline skipped: "
            "weekend."
        )

        return

    # --------------------------------------------------------
    # Prevent duplicate trigger during the same scheduler
    # window.
    # --------------------------------------------------------

    if (
        last_automatic_trigger_date
        == today
    ):

        return

    # --------------------------------------------------------
    # Prevent duplicate execution if today's pipeline already
    # completed.
    # --------------------------------------------------------

    last_run = (
        get_last_pipeline_date()
    )

    if last_run == today:

        print(
            "Automatic pipeline skipped: "
            "already completed today."
        )

        last_automatic_trigger_date = (
            today
        )

        return

    # --------------------------------------------------------
    # Prevent concurrent execution.
    # --------------------------------------------------------

    if pipeline_status["running"]:

        print(
            "Automatic pipeline skipped: "
            "pipeline already running."
        )

        return

    acquired = (
        pipeline_lock.acquire(
            blocking=False
        )
    )

    if not acquired:

        print(
            "Automatic pipeline skipped: "
            "pipeline lock is active."
        )

        return

    # Mark the trigger immediately so the scheduler
    # cannot trigger the same automatic job again.
    last_automatic_trigger_date = today

    print()
    print("=" * 70)
    print(
        "AUTOMATIC DAILY PIPELINE TRIGGERED"
    )
    print("=" * 70)

    thread = threading.Thread(

        target=run_pipeline_background,

        kwargs={
            "source": "automatic"
        },

        daemon=True
    )

    thread.start()


# ============================================================
# AUTOMATIC SCHEDULER
# ============================================================

def automatic_pipeline_scheduler():

    """
    Runs continuously in a background thread.

    Schedule:
        Monday-Friday
        15:45 IST

    The scheduler checks every 20 seconds.
    """

    scheduled_hour = 15
    scheduled_minute = 45

    print()
    print(
        "Automatic scheduler started."
    )

    while True:

        try:

            now = datetime.now(
                IST
            )

            # ------------------------------------------------
            # Monday-Friday
            # ------------------------------------------------

            if now.weekday() < 5:

                scheduled_time = time(
                    scheduled_hour,
                    scheduled_minute
                )

                current_time = now.time()

                window_start = (
                    scheduled_time
                )

                window_end = (
                    datetime.combine(
                        now.date(),
                        scheduled_time
                    )
                    + timedelta(
                        minutes=5
                    )
                ).time()

                # ------------------------------------------------
                # Trigger during the 15:45-15:50 window.
                # ------------------------------------------------

                if (
                    current_time >= window_start
                    and
                    current_time < window_end
                ):

                    start_automatic_pipeline()

            # ------------------------------------------------
            # Check every 20 seconds.
            # ------------------------------------------------

            time_module.sleep(
                20
            )

        except Exception as e:

            print(
                "Scheduler error:",
                e
            )

            time_module.sleep(
                30
            )